### ISSUE TITLE
Location based Metroid counter doesnt work backwards.

### ISSUE THREAD

**Issue by greennick78** [AM2R-Community-Developers/AM2R-Community-Updates#120]
**Describe the bug**
When the metroid counter is set to only show the amount of metroids in the area you're currently in it instead only shows the number of metroids in the farthest area you've gotten to.

**To Reproduce**
Get to any area except area 1 than go back to any area numbered lower than it (the previous area should have all metroids cleared while the higher numbered area should atleast have 1 metroid, I'm not sure if the lower numbered area needs to actually have all metroids cleared but since i was playing in the standard game mode i have no way to test it.) (Ex: go to area 8: the nest than instantly leave to do shinespark puzzle in area 1: golden temple, the metroid counter will still say 3)

**Expected behavior**
The metroid counter should reflect the number of metroids in the area you're currently in rather than the number of metroids in the highest numbered area you've visited.

**Media**
![image](https://user-images.githubusercontent.com/41275888/216800909-bb7a198c-6746-481a-b53f-631f50dced0d.png)
Note the number of metroids and the upgrades obtained.

**Platform (please complete the following information):**
 - OS: windows
 - Version: 1.55

**Game Version:**
1.55

**Additional context**
Was using a palette mod, playing the standard mode on normal difficulty.

**Comment by Lojemiru** [comment]
Completely intended. The title is a bit of a misnomer, and could use some adjustment though - it's for the number of Metroids required to lower the lava level, not within an "area" (as they are nebulously defined and have no actual code to check what "area" you're in).

Appreciate the report nonetheless though!
