### ISSUE TITLE
Change the icons for multiple items on 1 screen.

### ISSUE THREAD

**Issue by greennick78** [AM2R-Community-Developers/AM2R-Community-Updates#121]
**Is your feature request related to a problem? Please describe.**
Possible frustrations arise with certain items when going to backtrack

**Describe the solution you'd like**
The circle on the map that indicates where an uncollected or collected item is located should only fill halfway if theres 2 items on the same map block.

**Describe alternatives you've considered**
not having the dot become solid until ALL items on a map block are obtained, having the map dot be a different color for screens that have multiple items and filling all the way once a single item is collected to reduce amount of areas to check.

**Comment by Lojemiru** [comment]
We already do this as per alternative solution 1, as can be seen here:
![image](https://user-images.githubusercontent.com/33508026/216801255-e740142a-461e-4692-a50b-818414eccd46.png)

 Do you have a specific example where this isn't happening in 1.5.5?

**Comment by greennick78** [comment]
Huh, was i swear at one point in my run i collected one item on a block that had 2 items and the dot filled in. Might just have been my imagination then. Sorry for the inconvenience.

**Comment by Miepee** [comment]
> Huh, was i swear at one point in my run i collected one item on a block that had 2 items and the dot filled in. Might just have been my imagination then. Sorry for the inconvenience.

That probably was #106
