### ISSUE TITLE
Game runs slow when booted through the launcher

### ISSUE THREAD

**Issue by Minuir** [AM2R-Community-Developers/AM2R-Community-Updates#127]
When AM2R 1.5.5 is booted through the launcher (v.2.3.0), it runs very slow (high CPU usage (60%), high GPU usage (20%) -- all animations are slower by 50% or so), and the game has no sound.
I noticed "Antimalware Service Exectutable" being at 20% CPU usage.

When AM2R 1.1 is booted though the .exe, it runs great, but it has no sound. Also CPU and GPU usage are still high.
"Antimalware Service Exectutable" has normal CPU usage.

To solve the problem, I created a shortcut on the desktop through the option in the launcher. When AM2R 1.5.5 is booted through this shortcut, the game is running at normal speed, there is sound and CPU/GPU usage is low. Also "Antimalware Service Exectutable" has normal CPU usage.

**Platform:**
 - OS: Windows
 - Version: 10

**Game Version:**
AM2R 1.5.5

**Additionnal info:**
This was not happening 2 month earlier. I did not launch the game during 1 month and it happened when I lauched it again. I unfortunately can't tell what modifications were made to my computer during this time.

**Comment by Miepee** [comment]
Sounds like an issue you have with your anti-malware software. We can't do anything from that on the launcher side.
