### ISSUE TITLE
Don't understand directions.

### ISSUE THREAD

**Issue by godreborn** [AM2R-Community-Developers/AM2R-Community-Updates#128]
I'm not sure if I would consider this a bug, but I had trouble following the instructions earlier, mostly this one: Replace the two blank shader assets with default GM:S shader skeletons or your own copy of each shader, as well as the accompanying script files for the Retro Palette Swapper: pal_swap_init_system and pal_swap_set. WARNING: If the two above scripts are not replaced before opening the project file, GM:S 1.4 will replace them with <undefined> references in the asset tree at Scripts/Lojical/Shaders/. This will produce numerous seemingly unrelated errors until they are deleted and replaced with the appropriately named scripts.

I wasn't sure if I had to make "dummy" shaders and scripts, because that didn't work.  I still got about five errors with the scripts, which had nothing to do with the scripts I had created.  I just made blank scripts, wasn't sure what to put in them as I'm not a coder.  I also made some blank shaders, but both together wouldn't work, because they had the same names, so I was completely lost.  I'm actually trying to build for uwp, which I've built for before (other projects).  however, I was completely lost here.  if you could help, I'd be very grateful.

**Comment by Lojemiru** [comment]
Those shaders/scripts are paid assets, you should be able to look them up by name. You need to purchase said assets yourself and install them; using dummy scripts/shaders will _not_ work properly.

If you are targeting UWP for console port purposes, I request that you stop. We do not offer any form of support for putting AM2R on consoles, as that simply makes it a bigger target for potentially concerned parties.
