### ISSUE TITLE
Languages with non-latin characters are not displayed

### ISSUE THREAD

**Issue by Miepee** [AM2R-Community-Developers/AM2R-Community-Updates#44]
**Describe the bug**
Having a language with non-latin characters (like russian or japanese) won't display the characters at all.

**To Reproduce**
Open the game, and select a language with non-latin characters, like russian or japanese.

**Expected behavior**
The non-latin characters from the fonts will be used to display the font

**Media**
If applicable, add screenshots/videos to help explain your problem.
![jap](https://cdn.discordapp.com/attachments/396898995252756480/809867720043528221/unknown.png)
![rus](https://cdn.discordapp.com/attachments/396898995252756480/809867791497953320/unknown.png)

**Platform (please complete the following information):**
 - OS: Linux
 - Version: Arch

**Game Version:**
1.5.2

**Comment by Lojemiru** [comment]
This may be a combination of various bugs involving using the wrong font reference or a Linux font loading issue - I'll have to investigate multiple failure vectors. Writing this comment as a note for when I actually come around to it.

**Comment by Lojemiru** [comment]
Cannot replicate on personal hardware, and a code review checks out. Considering this an autopatcher/dependency problem until further information is provided.

**Comment by Miepee** [comment]
Got fixed when we build 1.5.3 / switched to VM builds.
