### ISSUE TITLE
Having long values in modifiers.ini results in a out-of-memory-crash.

### ISSUE THREAD

**Issue by Miepee** [AM2R-Community-Developers/AM2R-Community-Updates#46]
**Describe the bug**
Having long values in modifiers.ini results in a out-of-memory-crash.

**To Reproduce**
Just have a really long value in the modifiers.ini (in my testing, the resulted file was almost 2GB, this may happen sooner as well)

**Expected behavior**
No crash

**Platform (please complete the following information):**
 - OS: Windows
 - Version:10

**Game Version:**
1.5.2

**Additional context**
I'm not sure if this is actually fixable or not, since I'm pretty sure the crash occurs while trying to actually open the file.
Not sure, but maybe it's possible to check if the file has exceeded a specific length, and then delete it and start a new one?

**Comment by Lojemiru** [comment]
I didn't think GM:S had this functionality, but apparently we can check the binary size of a file: https://docs.yoyogames.com/source/dadiospice/002_reference/file handling/binary files/file_bin_size.html
