### ISSUE TITLE
Starting the game already full-screened produces graphical issues

### ISSUE THREAD

**Issue by Miepee** [AM2R-Community-Developers/AM2R-Community-Updates#48]
**Describe the bug**
When the game is starting in fullscreen mode, you get all kinds of garbage, including but not limited to:
-excerpts from currently other open windows
-random AM2R rooms
-coloured mess (sometimes seizure invoking)

**To Reproduce**
Start the game, set the display option to Fullscreen, save, exit and start the game again.

**Expected behavior**
Either don't produce garbage in fullscreen boot, or if that isn't possible:
1. Read that the current display option is fullscreen.
2. Start normally
3. After AM2R has been started, switch to fullscreen then automatically.

**Platform (please complete the following information):**
 - OS: Linux
 - Version: Mint 20.04, Arch

**Game Version:**
1.5.2

**Comment by Lojemiru** [comment]
Cannot directly fix - this is a general GM issue. Might be able to make the game not fullscreen immediately on boot, but I'm not even sure if that will fix the bug.

**Comment by Miepee** [comment]
> I'm not even sure if that will fix the bug.

Seeing as when you manually do this, it does fix it, I'd assume it would does fix when being done automatically as well.
