### ISSUE TITLE
Controller screen dpad scale issue

### ISSUE THREAD

**Issue by Lojemiru** [AM2R-Community-Developers/AM2R-Community-Updates#78]
See attached picture:
![](https://cdn.discordapp.com/attachments/409883727687319563/824814095239741500/glitch.png)

**Comment by Miepee** [comment]
Here is a very quick edit I made that fixed it
![grafik](https://user-images.githubusercontent.com/38186597/114385509-69597b80-9b90-11eb-8c0b-49542de7992a.png)

**Comment by Lojemiru** [comment]
This has unfortunately resulted in me realizing that there are a few pixel inconsistencies in the outline too that I'll need to correct. Those will be more difficult to work with, as the outline is a Photoshop glow, but I actually already have a project file set up for this that should allow me to do it fairly easily. Greatly appreciated edit though!

**Comment by Lojemiru** [comment]
Here is a (hopefully) finalized edit that fixes it along with some other inconsistencies I noted.
![bgController](https://user-images.githubusercontent.com/33508026/127760930-df2ca854-130d-42a2-981b-1341a7273815.png)
