### ISSUE TITLE
Use a checksum to detemine if the custom palette shader needs to be loaded. (Alternative fix for issue #77)

### ISSUE THREAD

**Issue by Jesright73** [AM2R-Community-Developers/AM2R-Community-Updates#89]
The palette shader is always active, resulting in poor performance on some systems.

When the game is launched, run a checksum on the custom palette image files in`\*AM2Rprofile*\mods\palettes\`. If the checksum matches that of the original palette files that are packaged in the _AM2R_11.zip_ source, the shader is not turned on.

The result should be less system resources required when not using custom palettes, better performance on low-spec hardware 

Could be a possible alternative solution to the problem identified in [Issue#77](https://github.com/AM2R-Community-Developers/AM2R-Community-Updates/issues/77#issue-839635688)

**Comment by Lojemiru** [comment]
Never mind, [Miles has informed me that I am very very wrong.](http://docs.yoyogames.com/source/dadiospice/002_reference/file%20handling/md5_file.html) This plus a toggle would probably be the best solution.

**Comment by Miepee** [comment]
Considering #77 has been closed, I don't think this alternative is necessary anymore.
