### ISSUE TITLE
Blob solid stays after killing it

### ISSUE THREAD

**Issue by Miepee** [AM2R-Community-Developers/AM2R-Community-Updates#94]
**Describe the bug**
Blob solid not being removed

**To Reproduce**
Used a pb and tried to move forward

**Expected behavior**
Blob solid should be removed

**Media**
![image](https://user-images.githubusercontent.com/38186597/125770819-8617ade9-bb9c-4ee5-80be-ce0be839f76d.png)

**Game Version:**
1.5.2

**Additional context**
GhostXor found it, if more info is needed one should contact him

**Comment by Lojemiru** [comment]
Unable to replicate. Unless I get more details this is going to have to be set aside.
