### ISSUE TITLE
Glasstown_NBP char error

### ISSUE THREAD

**Issue by Miepee** [AM2R-Community-Developers/AM2R-Community-Updates#96]
Lowercase letter `є` (U+0454) is displaying `э` instead.

**Media**
This is how it currently looks like:
![grafik](https://user-images.githubusercontent.com/38186597/126909155-7e7d58d8-5238-4c93-b444-ae681916cd4a.png)

This is how it should look like:
![grafik](https://user-images.githubusercontent.com/38186597/126908097-eda3d716-01da-40fd-bc37-56f0a9e6992b.png)

**Game Version:**
1.5.2

**Additional context**
Thanks for @drtwisted for finding this.

**Comment by Miepee** [comment]
Here's a TTF with that glyph fixed
[GlasstownNBP.zip](https://github.com/AM2R-Community-Developers/AM2R-Community-Updates/files/6913196/GlasstownNBP.zip)

**Comment by Lojemiru** [comment]
TTF added to the Windows and Linux autopatcher repositories. Marking as resolved.
